[package]
name = "game-of-poker"
version = "0.1.0"
authors = ["dymocaptin <peknudsen@gmail.com>"]

[dependencies]
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
names = { version = "0.14.0", default-features = false }